### ISSUE TITLE
Details for installing on windows

### ISSUE THREAD

**Issue by Jdash99** [marcopiraccini/electron-printer#2]
Can you give me a more detailed explanation of how to install this module.

This is the actual explanation:

> Use a Windows 7 on x64. Install Visual Studio (2013 is OK on Windows 7) and Python 2.7.x Always specify the VisualStudio version using `--msvs_version=xxxx`, foor instance`npm i --msvs_version=2013`
> 
> Release using `npm run release-win --msvs_version=2013` (x64) or `npm run release-win-ia32 --msvs_version=2013` (ia32)

I have these questions:
- It is not possible to install simply using `npm install electron-printer`?
- To build I need to download the zip, extract it and only then follow your instructions, right?
- If I have Win 10 (64 bits) and have installed visual studio community version 2015 do I have to use `npm run release-win --msvs_version=2015`?

These are basics questions, but i'm clueless right now...

Thanks for the help

**Comment by marcopiraccini** [comment]
The purpose of this module is to NOT build it locally. If you can do that, you can use directly the node-printer module. 
Simply use `npm install electron-printer --save`

**Comment by Jdash99** [comment]
OK thank you, I was able to use the node-printer module after all.
